In [1]:
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn

In [2]:
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]


In [3]:
#convert to floats
x=torch.tensor(x).float()
y=torch.tensor(y).float()



In [6]:
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


In [5]:
x=x.to(device)
y=y.to(device)

In [46]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
y = torch.tensor([[3],[7],[11],[15]])

In [47]:
#defind to get single item from dataset
class MyDataset(Dataset):
    def __init__(self,x,y):
        self.x=torch.tensor(x).float()
        self.y=torch.tensor(y).float()
    def __len__(self):
        return len(self.x)
    def __getitem__(self,idx):
        return self.x[idx], self.y[idx]


In [48]:
ds=MyDataset(x,y)


C:\Users\karti\AppData\Local\Temp\ipykernel_16908\1542342336.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x=torch.tensor(x).float()
C:\Users\karti\AppData\Local\Temp\ipykernel_16908\1542342336.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y=torch.tensor(y).float()


In [42]:
dl=DataLoader(ds,batch_size=1,shuffle=True)

In [43]:
dl

In [44]:
#fetching batches 
for a,b in dl:
    print(a,b)

tensor([[1., 2.]]) tensor([[1., 2.]])
tensor([[7., 8.]]) tensor([[7., 8.]])
tensor([[5., 6.]]) tensor([[5., 6.]])
tensor([[3., 4.]]) tensor([[3., 4.]])
