In [1]:
# building a neural network using Pytorch


In [3]:
import torch
#input x and output y
x=[[1,2],[3,4],[5,6],[7,8]]
y=[[3],[7],[11],[15]]


In [4]:
#convert to float and tensor
x=torch.tensor(x).float()
y=torch.tensor(y).float()

In [5]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [6]:
x=x.to(device)
y=y.to(device)

In [7]:
# define neural arch
import torch.nn as nn


In [14]:
class MyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__() #to ensure class inherits nn.Module

        #define layers
        self.input_to_hidden=nn.Linear(2,8)
        self.hidden_layer_activation=nn.ReLU()
        self.hidden_to_output=nn.Linear(8,1)

    #connect the layers
    def forward(self,x):
        x=self.input_to_hidden(x)
        x=self.hidden_layer_activation(x)
        x=self.hidden_to_output(x)
        return x


In [24]:
torch.manual_seed(42)
#let us inspect weights
#create instance of MyNeuralNet register it to device
mynet=MyNeuralNet().to(device)

In [25]:
mynet.input_to_hidden.weight

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323],
        [ 0.5224,  0.0958],
        [ 0.3410, -0.0998]], requires_grad=True)

In [26]:
#getting all params
mynet.parameters()

<generator object Module.parameters at 0x0000020FA7C73300>

In [28]:
#looping generator object
for par in mynet.parameters():
    print(par)

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323],
        [ 0.5224,  0.0958],
        [ 0.3410, -0.0998]], requires_grad=True)
Parameter containing:
tensor([ 0.5451,  0.1045, -0.3301,  0.1802, -0.3258, -0.0829, -0.2872,  0.4691],
       requires_grad=True)
Parameter containing:
tensor([[-0.2791, -0.1630, -0.0998, -0.2126,  0.0334, -0.3492,  0.3193, -0.3003]],
       requires_grad=True)
Parameter containing:
tensor([0.2730], requires_grad=True)


In [30]:
#You can also manually register these parameters
#using the nn.Parameter(<tensor>) function. Hence, the following code is equivalent to the neural network class that we defined previously.
class MyNeuralNet2(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_to_hidden_layer = nn.Parameter(torch.rand(2,8))
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Parameter(torch.rand(8,1))
    def forward(self, x):
        x = x @ self.input_to_hidden_layer
        x = self.hidden_layer_activation(x)
        x = x @ self.hidden_to_output_layer
        return x

In [9]:
nn.Linear(in_features=10,out_features=12,bias=True)

Linear(in_features=10, out_features=12, bias=True)